#===========================================================#
#      Configuration "riche" pour Minimal Mistakes          #
#===========================================================#

#----------- Informations de base -----------#
title: Mon Portfolio de Recherche
author: Mwnkr
description: "Une collection de mes explorations et démonstrations mathématiques personnelles."
url: "https://mwnkr.github.io" # Mettez votre URL

#----------- Thème et plugins -----------#
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-feed
  - jekyll-include-cache

#----------- Profil de l'auteur (barre latérale) -----------#
author:
  name: "Mwnkr"
  avatar: "/assets/images/kuriboh.png" # Chemin vers une image, à ajouter dans votre projet
  bio: "Passionné par les mathématiques et la résolution de puzzles combinatoires."
  location: "France"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/VOTRE-NOM-UTILISATEUR"
    # Ajoutez d'autres liens ici

#----------- Valeurs par défaut pour les articles -----------#
# C'est ici que la magie opère pour enrichir vos pages
defaults:
  # Pour tous les articles dans le dossier /_posts/
  - scope:
      path: ""
      type: posts
    values:
      layout: single # Le layout de base pour un article
      author_profile: true # AFFICHE la barre latérale de l'auteur
      show_date: true
      # --- Table des matières automatique ---
      toc: true # AFFICHE la table des matières
      toc_sticky: true # La rend flottante
      toc_label: "Sur cette page" # Titre de la table des matières
      toc_icon: "fas fa-stream" # Icône pour la table des matières

#----------- Page d'accueil (en mode grille) -----------#
# Pour utiliser ce mode, votre page index.html devra être modifiée
# Vous pouvez commencer par une page d'accueil simple et l'améliorer ensuite.

#----------- Configuration de la construction (Build) -----------#
# Moteur de Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  # --- LA LIGNE MAGIQUE ---
  # Indique à Kramdown de reconnaître et protéger les blocs MathJax
  #math_engine: mathjax

#----------- Pied de page -----------#
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/VOTRE-NOM-UTILISATEUR"
