#===========================================================#
#                   Bienvenue sur Jekyll!                   #
#         Configuration pour le thème "Hydejack"            #
#================================e==========================#

#----------- Informations de base du site -----------#
# Titre de votre site
title: Mon Portfolio de Recherche

# Nom de l'auteur
author: Mwnkr

# Description de votre site pour les moteurs de recherche
description: >- # la description peut s'étendre sur plusieurs lignes
  Une collection de mes explorations et démonstrations mathématiques personnelles.

# Langue du site
lang: fr

# URL complète de votre site (très important!)
# Remplacez par votre nom d'utilisateur GitHub
url: "https://VOTRE-NOM-UTILISATEUR.github.io"

#----------- Configuration de Hydejack -----------#
# Hydejack offre une version PRO avec plus de fonctionnalités.
# Pour la version gratuite, la configuration de base suffit.

# Apparence et logo
# accent_image: /assets/img/accent.png # Image décorative
# accent_color: '#268bd2' # Couleur d'accentuation si pas d'image

# Barre latérale (sidebar)
sidebar_sticky: true # Barre latérale fixe au défilement

# Auteur (affiché dans la barre latérale)
# Les informations sont reprises de la section `author:` plus bas.

# Police d'écriture (vous pouvez choisir des polices Google Fonts)
font: "Roboto"
font_heading: "Roboto Slab"

#----------- Plugins requis -----------#
# Hydejack utilise ces plugins. Assurez-vous qu'ils soient dans votre Gemfile.
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag # Très utile pour le référencement
  - jekyll-include-cache

#----------- Informations sur l'auteur (détaillées) -----------#
# Utilisé par jekyll-seo-tag et d'autres parties du thème
author:
  name: Mwnkr
  # email: votre.email@exemple.com
  # twitter: votrepseudo
  github: VOTRE-NOM-UTILISATEUR # Important pour les liens sociaux

# Liens sociaux affichés dans la barre latérale
social:
  github: VOTRE-NOM-UTILISATEUR
  # twitter: votrepseudo
  # linkedin: votre-profil
  # instagram: votrecompte

#----------- Configuration de la construction (Build) -----------#
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Exclure des fichiers de la construction
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE

#----------- Valeurs par défaut -----------#
# Définit la mise en page par défaut pour les différents types de contenu
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post # Hydejack utilise la mise en page "post"
      show_sidebar: true # Affiche la barre latérale sur les articles
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      show_sidebar: true # Ou `false` si vous ne voulez pas de barre latérale sur les pages
